config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'splashpage#splash'

  # Home page (categories page)
  resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :expenses, only: [:new, :create, :edit, :update, :destroy]
  end

  # Transactions page
  resources :expenses, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  get 'add_new_category', to: 'groups#new'

  get 'add_new_transaction', to: 'expenses#new'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all

    return unless user.present?

    can :create, Group
    can :create, Expense

    can :destroy, Group, user_id: user.id
    can :destroy, Expense, user_id: user.id

    return unless user.admin?

    can :manage, :all

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :group
  validates :name, :amount, :date, presence: true
  validates :name, length: { maximum: 50 }
  validates :amount, numericality: true
  validates :group_id, presence: true
  validates :amount, presence: true,
                     numericality: { greater_than_or_equal_to: -10_000_000, less_than_or_equal_to: 10_000_000 }
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :expenses
  belongs_to :user
  has_one_attached :icon

  validates :name, presence: true
  validate :valid_icon_url_or_attachment

  private

  def valid_icon_url_or_attachment
    return if icon.attached?

    errors.add(:base, 'You must provide an icon URL or upload an icon image')
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :expenses, foreign_key: :author_id, dependent: :destroy
  has_many :groups
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :current_password) }
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[new create]
  before_action :set_expense, only: %i[edit update destroy]

  def index
    @expenses = current_user.expenses.order(date: :desc)
  end

  def new
    @expense = @group.expenses.build
  end

  def create
    @expense = @group.expenses.build(expense_params)
    @expense.author_id = current_user.id
    if @expense.save
      redirect_to group_path(@group), notice: 'Expense created successfully.'
    else
      render :new
    end
  end

  def edit
    @expense = current_user.expenses.find(params[:id])
    @group = @expense.group
  end

  def update
    if @expense.update(expense_params)
      redirect_to group_path(@expense.group), notice: 'Expense updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @expense.destroy
    redirect_to group_path(@expense.group), notice: 'Expense deleted successfully.'
  end

  private

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end

  def set_expense
    @expense = current_user.expenses.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, :group_id, :date)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups.order(updated_at: :desc)
  end

  def show
    @group = current_user.groups.find(params[:id])
    @expenses = @group.expenses.order(date: :desc)
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    if @group.expenses.any?
      redirect_to groups_path,
                  alert: 'Please move or delete the transactions before deleting the category.'
    else
      @group.destroy
      redirect_to groups_path, notice: 'Category deleted successfully.'
    end
  end

  def update
    @group = current_user.groups.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path, notice: 'Category updated successfully.'
    else
      render :edit
    end
  end

  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to groups_path, notice: 'Group created successfully.'
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splashpage_controller.rb
class SplashpageController < ApplicationController
  def splash
    return unless user_signed_in?

    redirect_to groups_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/expenses/edit.html.erb
<%= form_with(model: [@group, @expense], url: group_expense_path(@group, @expense), method: :patch) do |form| %>

<nav class="navbar navbar-expand-lg navcolor">
  <%= link_to group_path(@group) do %>
    <%= image_tag "arrow_back.svg", class: "arrow-back" %>
  <% end %>
  <h4 id="headingcat">Edit Expense</h4>
  <div class="actions">
    <%= form.submit "Save", class: 'registration-submission' %>
  </div>
</nav>
<div class="new_expense_form">
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount %>
    <%= form.number_field :amount, step: '0.01' %>
  </div>

  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :group_id, "Category" %>
    <%= form.collection_select :group_id, current_user.groups, :id, :name %>
  </div>
</div>
<% end %>

app/views/expenses/index.html.erb
<%= render partial: 'shared/navbar/navbar3' %>
<div class="transactions-page">
<% @expenses.each do |expense| %>
  <div class="transaction-card">
    <% if expense.group.icon.attached? %>
      <%= image_tag url_for(expense.group.icon), class: "group-icon" %>
    <% else %>
      <p>No icon available</p>
    <% end %>
    <div class="transaction-card-details">
    <p><%= expense.group.name %></p>
    <p class="dateoftransaction"><%= expense.date.strftime("%B %d %Y") %></p></div>
    <p><strong>$<%= number_with_precision(expense.amount, precision: 2) %></strong></p>
    
  </div>
<% end %>

<% if @expenses.empty? %>
  <p>No transactions yet</p>
<% end %>
</div>

app/views/expenses/new.html.erb
<%= form_with(model: [@group, @expense], url: group_expenses_path(@group), method: :post) do |form| %>

<nav class="navbar navbar-expand-lg navcolor">
  <%= link_to group_path(@group) do %>
    <%= image_tag "arrow_back.svg", class: "arrow-back" %>
  <% end %>
  <h4 id="headingcat">Add a new transaction</h4>
  <div class="actions">
    <%= form.submit "Save", class: 'registration-submission' %>
  </div>
</nav>
<div class="new_expense_form">
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount %>
    <%= form.number_field :amount, step: '0.01' , min: -10000000, max: 10000000 %>
  </div>

    <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :group_id, "Category" %>
    <%= form.collection_select :group_id, current_user.groups, :id, :name, { prompt: "Select category" } %>
  </div>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>
      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/groups/edit.html.erb
<%= form_with(model: @group, url: group_path(@group), method: :patch) do |form| %>
<nav class="navbar navbar-expand-lg navcolor">
  <%= link_to groups_path do %>
    <%= image_tag "arrow_back.svg", class: "arrow-back" %>
  <% end %>
  <h2 id="headingcat">Edit Category</h2>
  <div class="actions">
    <%= form.submit "Save", class: 'registration-submission' %>
  </div>
</nav>
<div class="new_expense_form">
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.file_field :icon %>
  </div>
</div>
<% end %>

app/views/groups/index.html.erb
<%= render partial: 'shared/navbar/navbar1' %>

<div class="category-page">
  <div class="category-container">
  <% @groups.each do |group| %>
    <div class="category-card">
      <div class="category-card-details">
      <%= link_to group_path(group) do %>
        <% if group.icon.attached? %>
          <%= image_tag url_for(group.icon), id: "category-icon" %>
        <% else %>
          <p>There is no image</p>
        <% end %>
      <% end %>
      
      <h6><%= group.name %></h6>
      <p>$<%= number_with_precision(group.expenses.sum(:amount), precision: 2) %></p>
      </div>
      <div class="category-card-buttons">
      <%= link_to "Edit", edit_group_path(group), class:"editbtn" %>
      <%= button_to "Delete", group_path(group), class:"deletebtn", method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" } %>
      </div>
    </div>
  <% end %>
<div id="total-budget">
  TOTAL BUDGET AVAILABLE: <strong>$<%= number_with_precision(@groups.sum { |group| group.expenses.sum(:amount) }, precision: 2) %></strong>
</div>
<button id="add-category">
  <%= link_to "Add", new_group_path, id:"add" %>
</button>
  </div>
</div>

app/views/groups/new.html.erb
<%= form_with(model: @group, url: groups_path, method: :post) do |form| %>
<nav class="navbar navbar-expand-lg navcolor">
  <%= link_to groups_path do %>
    <%= image_tag "arrow_back.svg", class: "arrow-back" %>
  <% end %>
  <h2 id="headingcat">Add a new category</h2>
  <div class="actions">
    <%= form.submit "Save", class: 'registration-submission' %>
  </div>
</nav>
  <div>
    <%= form.text_field :name, placeholder:"Name" %>
  </div>

  <div>
    <%= form.file_field :icon %>
  </div>

 
<% end %>

app/views/groups/show.html.erb
<%= render partial: 'shared/navbar/navbar2' %>
<div id="groupdetailspage">
  <div class="category-container">
<div class="group-details-card">
  <div class="group-details-iconname">
<% if @group.icon.attached? %>
  <%= image_tag url_for(@group.icon), class: "group-icon" %>
<% else %>
  <p>No icon available</p>
<% end %>

<h5><%= @group.name %> </h5>
</div>


<% @expenses.each do |expense| %>
<hr>
  <div>
    <p><strong>Name:</strong> <%= expense.name %></p>
   <%= expense.date %></p>
    <p><strong>Amount:</strong> <%= number_with_precision(expense.amount, precision: 2) %></p>
    <div class="category-card-buttons">
    <%= link_to "Edit", edit_group_expense_path(@group, expense), class:"editbtn" %>
     <%= button_to "Delete", group_expense_path(@group, expense), class:"deletebtn", method: :delete, data: { confirm: "Are you sure?" } %>
     </div>
  </div>
 
<% end %>
<hr>
<p><strong>TOTAL PAYMENT</strong>  <strong>$<%= number_with_precision(@group.expenses.sum(:amount), precision: 2) %></strong></p>
</div>
<button id="add-category">
<%= link_to "Add a new transaction", new_group_expense_path(@group), id:"add" %>
</button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>

       <% unless current_page?(new_user_registration_path) || current_page?(new_user_session_path) %>
      <% end %>

    <%= yield %>
 <div class="push-content">
<% if user_signed_in? %> 
    <div id="notice-container" class="notice-container">
  <p class="notice"><%= notice %></p>
</div>
  <div id="alert-container" class="alert-container">
    <p class="alert"><%= alert %></p>
    </div>
  <% end %>
</div>
  </body>
</html>

app/views/shared/navbar/_loginnav.html.erb
<nav class="navbar navbar-expand-lg navcolor">
  <%= link_to root_path do %>
    <%= image_tag "arrow_back.svg", class: "arrow-back" %>
  <% end %>
  <h2 id="headingcat">LOGIN</h2>
  <div class="actions">
    <%= button_tag "Next", type: 'submit', form: 'new_user', class: 'registration-submission' %>
  </div>
</nav>

app/views/shared/navbar/_navbar1.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-expand-lg navcolor">
  <div class="container-fluid navcustom">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <%= image_tag "menu.svg", class:"navbar-toggler-icon" %>
    </button>
    <h2 id="headingcat">Categories</h2>
    <%= image_tag "search.svg", class:"search" %>
    <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
      
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <div class="userface">
        <%= image_tag "face.svg", class:"default_profile" %>
        
        <%= current_user.name %>
        </div>
        
        <li class="nav-item navis">
          <%= image_tag "settings.svg",id:"logo-svg" %><%= link_to "Account settings", edit_user_registration_path, class: "nav-link" %>
          
        </li>
        <hr>
        <li class="nav-item navis">
          <%= image_tag "category.svg" %><%= link_to "Categories", root_path, class: "nav-link" %>
        </li>
          <hr>    
        <li class="nav-item navis">
          <%= image_tag "shopping_bag.svg" %><%= link_to "List all transactions", expenses_path, class: "nav-link" %> 
        </li>
        <hr>
        <li class="nav-item navis">
          <%= image_tag "logout.svg" %><%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link", id: "logout-button" %>
        </li>
        <hr>
      </ul>
      
      </button>
    </div>
  </div>
</nav>
<% end %>

app/views/shared/navbar/_navbar2.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-expand-lg navcolor">
  <%= link_to groups_path do %>
      <%= image_tag "arrow_back.svg", class: "arrow-back" %>
    <% end %>
    <h2 id="headingcat">DETAILS</h2>
    <div></div>
  </nav>
<% end %>

app/views/shared/navbar/_navbar3.html.erb
<nav class="navbar navbar-expand-lg navcolor">
  <div class="container-fluid navcustom">
    <div id="separate-nav">
      <div id="separate-nav1">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <%= image_tag "menu.svg", class:"navbar-toggler-icon" %>

    </button>
    <h6 id="headingcat">TRANSACTIONS</h6>
     
    <%= image_tag "search.svg", class:"search" %>
</div>
<div id="separate-nav2">
    <h6 id="most-recent">Most recent</h6>
</div>
    <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <div class="userface">
          <%= image_tag "face.svg",class:"default_profile" %>
          <%= current_user.name %>
        </div>
        <li class="nav-item navis">
          <%= image_tag "settings.svg",id:"logo-svg" %><%= link_to "Account settings", edit_user_registration_path, class: "nav-link" %>
        </li>
        <hr>
        <li class="nav-item navis">
          <%= image_tag "category.svg" %><%= link_to "Categories", root_path, class: "nav-link" %>
        </li>
        <hr>    
        <li class="nav-item navis">
          <%= image_tag "shopping_bag.svg" %><%= link_to "List all transactions", expenses_path, class: "nav-link" %> 
        </li>
        <hr>
        <li class="nav-item navis">
          <%= image_tag "logout.svg" %><%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link", id: "logout-button" %>
        </li>
        <hr>
      </ul>
    </div>
  </div>
  </div>
</nav>

app/views/shared/navbar/_registernav.html.erb
<nav class="navbar navbar-expand-lg navcolor">
  <%= link_to groups_path do %>
    <%= image_tag "arrow_back.svg", class: "arrow-back" %>
  <% end %>
  <h2 id="headingcat">REGISTER</h2>
  <div class="actions">
    <%= button_tag "Next", type: 'submit', form: 'new_user', class: 'registration-submission' %>
  </div>
</nav>

app/views/shared/navbar/_updateaccnav.html.erb
<nav class="navbar navbar-expand-lg navcolor">
  <%= link_to root_path do %>
    <%= image_tag "arrow_back.svg", class: "arrow-back" %>
  <% end %>
  <h6 id="headingcat">EDIT ACCOUNT</h6>
  <div class="actions">
    <%= button_tag "Update", type: 'submit', form: 'edit_user', class: 'registration-submission' %>
  </div>
</nav>

app/views/splashpage/splash.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Splash Screen</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>
<body>
  <div class="container_splash">
    <%= image_tag "BUDGETTO.svg", class: "logo_splash" %>
      <div class="hold_buttons_splash">
        
        <%= link_to "Log in", new_user_session_path, class: "login_splash_button" %>
        <%= link_to "Sign up", new_user_registration_path, class: "sign_splash_button" %>
      </div>
    
  </div>
</body>
</html>